### ISSUE TITLE
Error handling message field in bad format

### ISSUE THREAD

**Issue by jhiemer** [evoila/osb-backup-agent#1]
When receiving an error message because a failed backup the response looks as follows:

```json
{
    "message": "backup failed.",
    "state": "backup",
    "error message": "File not found: /var/vcap/store/backup-agent/backup/localhost_2018_11_3_DD69H8D3-7876-4056-A0EE-DE8D3498259T.tar.gz"
}
```
The field `error message` should be `error_message`.

**Comment by marberger** [comment]
Changed struct to return json with 'error_message' instead of 'error message'. 
See commit c464087c80989d9b981d6d0660ca6009466d8ea0
